


'''
Utility class that can be used to visualize/draw occupency grids generated by this fastslam implementation.
'''
class MapViewerTool(object):

	def __init__(self):
		pass

	def draw_map(self, grid):
		pass

	def draw_map_with_history(self,)